USE master;
GO
IF DB_ID('PharmacyDB') IS NOT NULL
BEGIN
    ALTER DATABASE PharmacyDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PharmacyDB;
END
GO
CREATE DATABASE PharmacyDB;
GO
ALTER DATABASE PharmacyDB SET READ_COMMITTED_SNAPSHOT ON;
GO
USE PharmacyDB;
GO
CREATE TABLE Prak2BD (
    MedicineID INT IDENTITY(1,1) PRIMARY KEY,
    MedicineName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    Price DECIMAL(10,2) NOT NULL CHECK (Price >= 0),
    Quantity INT NOT NULL CHECK (Quantity >= 0),
    ExpirationDate DATE NOT NULL
);
GO
SELECT 'Prak2BD создана' AS Status;
GO