USE master;
GO
IF DB_ID('UniversityDB') IS NOT NULL
BEGIN
    ALTER DATABASE UniversityDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE UniversityDB;
END
GO
CREATE DATABASE UniversityDB;
GO
ALTER DATABASE UniversityDB SET READ_COMMITTED_SNAPSHOT ON;
GO
USE UniversityDB;
GO
CREATE TABLE Students (
    StudentID INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    BirthDate DATE NOT NULL CHECK (BirthDate <= CAST(GETDATE() AS DATE)),
    GroupName NVARCHAR(20) NOT NULL DEFAULT N'ИС-1'
);
GO
CREATE TABLE Courses (
    CourseID INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Hours INT NOT NULL CHECK (Hours > 0),
    IsActive BIT NOT NULL DEFAULT 1 CHECK (IsActive IN (0,1))
);
GO
CREATE TABLE Enrollments (
    EnrollmentID INT IDENTITY(1,1) PRIMARY KEY,
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    EnrollDate DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Enrollments_Students FOREIGN KEY (StudentID) REFERENCES Students(StudentID) ON DELETE CASCADE,
    CONSTRAINT FK_Enrollments_Courses FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE
);
GO
SELECT 'БД UniversityDB создана' AS Status;
GO